object BuildParams {
  const val KOTLINX_COROUTINES_RELEASE_TAG = "1.6.4"
  const val KOTLINX_SERIALIZATION_RELEASE_TAG = "v1.5.0"
  const val KOTLINX_DATETIME_RELEASE_TAG = "v0.4.0"

  const val SEARCH_APP_ID = "7961PKYRXV"
  const val SEARCH_INDEX_NAME = "prod_KOTLINLANG_WEBHELP"
}
