object BuildParams {
  const val DOKKA_TEMPLATES_VERSION = "1.9.10"

  const val KOTLINX_COROUTINES_RELEASE_TAG = "1.9.0-RC"
  const val KOTLINX_SERIALIZATION_RELEASE_TAG = "v1.7.0-RC"
  const val KOTLINX_DATETIME_RELEASE_TAG = "v0.6.0"
  const val KOTLINX_METADATA_JVM_RELEASE_TAG = "v0.9.0"

  const val SEARCH_APP_ID = "7961PKYRXV"
  const val SEARCH_INDEX_NAME = "prod_KOTLINLANG_WEBHELP"
}
