nodeLinker: node-modules

npmScopes:
  webteam:
    npmAlwaysAuth: true
    npmAuthToken: "${WEBTEAM_UI_NPM_TOKEN}"
    npmRegistryServer: "https://packages.jetbrains.team/npm/p/wt/npm/"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
