services:
  reverse-proxy:
    image: nginx:stable-alpine
    command: |
      sh -c '
        cat > /etc/nginx/conf.d/default.conf <<EOF
        server {
          listen 80;
          listen [::]:80;
      
          access_log off;

          location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
          }

          location = /50x.html {
            root /usr/share/nginx/html;
          }
        }
      EOF
      nginx -g "daemon off; error_log /dev/null;"
      '
    ports:
      - "3000:80"
    networks:
      - test-network
    volumes:
      - ./dist:/usr/share/nginx/html
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost" ]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "none"

  playwright:
    image: mcr.microsoft.com/playwright:v1.57.0-noble
    environment:
      BASE_URL: "http://reverse-proxy"
      WEBTEAM_UI_NPM_TOKEN: ${WEBTEAM_UI_NPM_TOKEN}
      CI: ${CI}
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "yarn install --immutable && yarn run test:ci"
    depends_on:
      reverse-proxy:
        condition: service_healthy
    networks:
      - test-network

networks:
  test-network:
