- from:
   - /docs/diagnostics/experimental-coroutines/index.html
   - /docs/reference/coroutines.html
  to: /docs/reference/coroutines-overview.html

- from: /docs/tutorials/coroutines-basic-jvm.html
  to: /docs/tutorials/coroutines/coroutines-basic-jvm.html

- from: /docs/reference/collections.html
  to: /docs/reference/collections-overview.html

- from: /docs/reference/experimental.html
  to: /docs/reference/opt-in-requirements.html

- from: /docs/resources.html
  to: https://kotlin.link/

- from: /community.html
  to: /community/

- from:
   - /user-groups/user-group-list.html
   - /community/user-groups.html
  to: /community/user-groups/

- from:
   - /docs/events.html
   - /community/talks.html
   - /community/events.html
  to: /community/events/

- from:
   - /community/kotlin-nights/guidelines.html
   - /community/kotlin-nights/branding.html
  to: /docs/kotlin-night-guidelines.html

- from: /community/slackccugl.html
  to: /docs/slack-code-of-conduct.html

- from: /docs/reference/compatibility.html
  to: /docs/reference/evolution/components-stability.html

- from: /kotlin-premier-event-2021/
  to: https://pages.jetbrains.com/kotlin-premier-event-2021/website

# Moved foundation to separate domain KTL-603

- from: /docs/kotlin-foundation.html
  to: https://kotlinfoundation.org/

- from: /docs/guidelines.html
  to: https://kotlinfoundation.org/guidelines/

- from: /docs/language-committee-guidelines.html
  to: https://kotlinfoundation.org/language-committee-guidelines/

- from: /docs/submitting-incompatible-changes.html
  to: https://kotlinfoundation.org/submitting-incompatible-changes/

- from: /docs/foundation-faq.html
  to: https://kotlinfoundation.org/faq/