import { expect, test } from '@playwright/test';
import { checkScreenshot, skipProduction, testSelector } from '@/test/utils';
import { ELEMENT_PADDING_OFFSET, RESOLUTIONS } from '../../visual-constants';
import { WebHelpPage } from '../page';
import { bodyOf, deflistIn, expandItem, itemsOf, pixelValue, TEST_PAGE_URL } from './utils';

test.describe('Docs: Test Page clear definition list', async () => {
    skipProduction();

    test.beforeEach(async ({ page }) => {
        const webHelpPage = new WebHelpPage(page, TEST_PAGE_URL);
        await webHelpPage.init();
    });

    test(`Should render clear definition list without numbering`, async ({ page }) => {
        const deflist = deflistIn(page, 'clear-definition-list');

        await expect(deflist).toBeVisible();
        await expect(deflist).toContainClass('definition-list--appearance-clear');
        await expect(deflist).not.toContainClass('definition-list--numbered');

        const items = itemsOf(deflist);
        await expect(items).toHaveCount(3);

        // without numbering there is no number gutter in front of the title
        await expect(deflist.locator(testSelector('definition-list-title-text')).first()).toHaveCSS(
            'padding-left',
            '0px'
        );

        const item = items.first();
        await expect(bodyOf(item)).toBeHidden();

        await expandItem(item);
        await expect(item.locator(testSelector('definition-list-description'))).toBeVisible();
    });

    test(`Should render numbered clear definition list`, async ({ page }) => {
        const numbered = deflistIn(page, 'numbered-clear-definition-list');

        await expect(numbered).toBeVisible();
        await expect(numbered).toContainClass('definition-list--appearance-clear');
        await expect(numbered).toContainClass('definition-list--numbered');

        // 11 items, so that two-digit numbers are rendered as well
        await expect(itemsOf(numbered)).toHaveCount(11);

        // the numbers are generated by a css counter, hence the gutter is asserted instead of the text
        const numberedTitle = numbered.locator(testSelector('definition-list-title-text')).first();
        await expect(numberedTitle).toHaveCSS('padding-left', '30px');
        await expect(numberedTitle).toHaveCSS('text-indent', '-30px');

        const plainTitle = deflistIn(page, 'clear-definition-list')
            .locator(testSelector('definition-list-title-text'))
            .first();
        expect(await pixelValue(numberedTitle, 'padding-left')).toBeGreaterThan(
            await pixelValue(plainTitle, 'padding-left')
        );
    });

    test(`Should restart numbering in every numbered definition list`, async ({ page }) => {
        const numbered = page.locator('dl.definition-list--numbered');
        await expect(numbered).toHaveCount(2);

        // the counter is reset on the list itself, so the practice list doesn't continue the previous one
        for (const deflist of await numbered.all()) {
            await expect(deflist).toHaveCSS('counter-reset', 'definition-list-item 0');
            await expect(deflist.locator(testSelector('definition-list-title')).first()).toHaveCSS(
                'counter-increment',
                'definition-list-item 1'
            );
        }
    });

    for (const [resolutionName, resolution] of Object.entries(RESOLUTIONS)) {
        test(`Should render clear definition list properly on ${resolutionName}`, async ({ page }) => {
            await page.setViewportSize(resolution);
            const element = deflistIn(page, 'clear-definition-list');
            await expect(element).toBeVisible();
            await element.scrollIntoViewIfNeeded();
            await checkScreenshot(element, { clip: ELEMENT_PADDING_OFFSET });
        });

        test(`Should render numbered definition list properly on ${resolutionName}`, async ({ page }) => {
            await page.setViewportSize(resolution);
            const element = deflistIn(page, 'numbered-clear-definition-list');
            await expect(element).toBeVisible();
            await element.scrollIntoViewIfNeeded();
            // the list has 11 items, so the screenshot covers two-digit numbers as well
            await checkScreenshot(element, { clip: ELEMENT_PADDING_OFFSET });
        });

        test(`Should render expanded numbered definition list properly on ${resolutionName}`, async ({ page }) => {
            await page.setViewportSize(resolution);
            const element = deflistIn(page, 'numbered-clear-definition-list');

            // the last item has a long title, which has to wrap without breaking the number gutter
            const item = itemsOf(element).last();
            await expandItem(item);

            await element.scrollIntoViewIfNeeded();
            await checkScreenshot(element, { clip: ELEMENT_PADDING_OFFSET });
        });
    }
});
