# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout doc repository
        uses: actions/checkout@v2
        with:
          path: main
      
      - name: Checkout verifier
        uses: actions/checkout@v2
        with:
          repository: AlexanderPrendota/kotlin-samples-verifier
          ref: feature_commits
          path: verifier
          
      - name: Run a one-line script
        run: echo ${{ join(github.event.commits.*.id, ' ' ) }}
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./verifier/gradlew
      - name: Build with Gradle
        working-directory: ./verifier
        run: |
             ./gradlew build -x test
             ./gradlew installDist
        
      - name: Run a docker with compiler-server
        working-directory: ./verifier
        run: ./gradlew dockerRun
      - name: Run verifier
        working-directory: ./verifier
        run: ./client/build/install/client/bin/client collect -r https://github.com/${{github.repository}} -f run-kotlin -commits ${{ github.event.before }},${{ github.event.after }} -out snippets
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: extracted-snippets
          path: ./verifier/snippets
          retention-days: 5
      
      - name: Checkout pusher
        uses: actions/checkout@v2
        with:
          repository: vmishenev/kotlin-samples-pusher
          path: pusher
          
      - name: Move a file
        run: mv ./verifier/snippets ./pusher/snippets
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./pusher/gradlew
        
      - name: Build with Gradle
        working-directory: ./pusher
        run: |
             ./gradlew build -x test
             ./gradlew installDist

      - name: Run verifier
        working-directory: ./verifier
        run: ./client/build/install/client/bin/client -in snippets -r https://github.com/vmishenev/kotlin-compiler-server -username ${{ secrets.TOKEN }}
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
