name: Validate universities

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_universities_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: 'v4.9.5'
      - run: |
         jsonschema -i <(yq eval --tojson -j data/universities.yml) data/schemas/universities.json
         echo "Universities data is valid!"
