name: Validate Case Studies Data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_case_studies_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: 'v4.9.5'
      - run: |
         jsonschema -i <(yq eval --tojson -j data/case-studies/case-studies.yml) data/schemas/case-studies.json
         echo "case studies data is valid!"
